 services:
  laravel-muiltivendor-app:
    build:
      context: .
      dockerfile: docker/dev/php/php.dockerfile
    volumes:
      - ./src:/var/www/html
    command: >
      sh -c "chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache && php-fpm"
    networks:
      - proxy_network

  nginx:
    image: nginx:latest
    ports:
      - "85:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/dev/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - proxy_network
    depends_on:
      - laravel-muiltivendor-app

  vite:
    image: node:20-alpine
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=200
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173 --strictPort"
    networks:
      - proxy_network

  artisan:
    build:
      context: ./src
      dockerfile: ../docker/dev/artisan/artisan.dockerfile
    volumes:
      - ./src:/var/www/html
    networks:
      - proxy_network
    depends_on:
      - laravel-muiltivendor-app

  composer:
    image: composer:latest
    container_name: composer-muiltivendor
    volumes:
      - ./src:/app
    working_dir: /app
    command: install
    networks:
      - proxy_network
 networks:
  proxy_network:
    external: true

 volumes:
   mssql_data:
